We have adopted this global online Privacy Policy to explain how we store and use personal and non-personal information we collect online on our websites, during your use of our online products and/or services (including online game play) and on mobile platforms.
EA collects both personal and non-personal consumer information.
When you use EA online and mobile products and services or you play our games on your PC or game system, we may collect certain non-personally identifiable information for purposes including improving our products and services, troubleshooting bugs, providing services to you, facilitating the provision of software updates, dynamically served content and product support as well as communicating with you.
EA's websites, online or mobile products or services may employ proprietary or third party ad serving technologies that use cookies, clear GIFs, web beacons, tracking pixels or other technologies to collect information as a result of ad serving through our products or services as well as to help track results.
EA uses the collected information for the prevention of fraud, and for authentication purposes.
You may also opt in to allow EA to share your personal information with companies and organizations that provide products or services that we believe may be of interest to you.
From time to time, EA employs third party contractors to collect personal information on our behalf to provide email delivery, product, prize or promotional fulfillment, contest administration, credit card processing, shipping or other services on our sites.
When an EA online or mobile product or service does request age information, and users identify themselves as under 13, the product or service will either block such users from providing personal information, or we will ensure consent is obtained from parents for the collection, use and sharing of their children's personal information.
If you visit a third party website that is linked to an EA site, you should consult that site's privacy policy before providing any personal information.
In the unlikely event that EA cannot resolve a concern to your satisfaction (or if EA cannot resolve a concern it has with you after attempting to do so informally), then you and EA agree to be bound by the following procedure to resolve any and all disputes between us.