If you do not agree to this Privacy Policy, do not use any of our Services or give us any of your information.
In addition to any Personal Information or other information that you choose to submit to us, we and our third-party service providers may use a variety of technologies that automatically (or passively) collect certain information whenever you visit or interact with the Services (" Usage Information").
If you choose to disable cookies or Flash cookies on your Device, some features of the Services may not function properly or may not be able to customize the delivery of information to you.
We may combine the information we receive from those sources with information we collect through the Services.
Except as otherwise permitted in this Privacy Policy, we will not share this information with third parties for any purpose and will only use this information for the sole purpose of providing you with the ability to request transportation via Uber's Mobile Application.
uploaded photos, posted reviews or comments, or information about you or your ride that you choose to share with others through features which may be provided on our Services.
We may provide these vendors with access to user information, including Personal Information, this information sharing is limited to only the information needed by the vendor to carry out the services they are performing for you or for us.
If you elect to register for products and/or services through the Co-Branded Services, you may be providing your information to both us and the third party.
The information used for targeted advertising either comes from us or through third party website publishers.
The Services may contain content that is supplied by a third party, and those third parties may collect web site usage information and your Device Identifier when web pages from any online or mobile Services are served to your browser.